name: redux_reins
description: TODO
version: 0.0.1
author: Ryunosuke Watanabe<heavenosk@gmail.com>
homepage: https://github.com/heavenosk/redux_reins
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  rxdart: ^0.23.1
  provider: ^4.0.3
  meta:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
