name: redux_reins
description: TODO
version: 0.0.1
author: Masayuki Ono <mono0926@gmail.com>
homepage: https://github.com/mono0926/redux_reins
environment:
  sdk: ">=2.5.0 <3.0.0"
dependencies:
  rxdart: ^0.23.1
  meta:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
